不可使用 df1.reindex , 因為 reindex 可能用在很多個欄位，但我們只想選擇其中幾個。
單純改名要使用 stock_price.columns= ['台積電','聯電','聯發科','鴻海']

In [83]:
import pandas as pd
import pandas_datareader.data as pdr
import yfinance as yf
yf.pdr_override()
all_data = {item:pdr.get_data_yahoo(item) for item in ['2330.TW','2303.TW','2454.TW','2317.TW']}
stock_price= pd.DataFrame({key:df['Adj Close'] for key,df in all_data.items()})
stock_price.columns= ['台積電','聯電','聯發科','鴻海']
stock_price.iloc[-20:]

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

                   台積電         聯電     聯發科     鴻海
Date
2024-05-23  871.631104  56.000000  1205.0  173.0
2024-05-24  863.661926  54.599998  1195.0  176.0
2024-05-27  865.654236  56.599998  1285.0  185.0
2024-05-28  861.669617  56.400002  1310.0  185.5
2024-05-29  853.700439  55.900002  1290.0  180.5
2024-05-30  834.773560  55.799999  1290.0  176.5
2024-05-31  817.838989  55.000000  1235.0  172.0
2024-06-03  842.742737  55.000000  1270.0  176.5
2024-06-04  835.769714  54.299999  1240.0  171.0
2024-06-05  850.711975  53.500000  1230.0  175.5
2024-06-06  890.557983  54.200001  1290.0  177.5
2024-06-07  875.615723  55.099998  1275.0  177.5
2024-06-11  879.600281  55.099998  1270.0  180.5
2024-06-12  905.500183  54.900002  1300.0  187.5
2024-06-13  919.000000  56.400002  1385.0  192.0
2024-06-14  922.000000  56.299999  1395.0  198.0
2024-06-17  921.000000  56.700001  1380.0  200.0
2024-06-18  943.000000  56.799999  1405.0  198.5
2024-06-19  981.000000  56.799999  1485.0  203.0
2024-06-20  972.000000  57.000000  1485.0  209.0